/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppReportsIndexRouteImport } from './routes/_app.reports.index'
import { Route as AppPromotionsIndexRouteImport } from './routes/_app.promotions.index'
import { Route as AppEmployeesIndexRouteImport } from './routes/_app.employees.index'
import { Route as AppAnalyticsIndexRouteImport } from './routes/_app.analytics.index'
import { Route as AppEmployeesIdRouteImport } from './routes/_app.employees.$id'
import { Route as AppSettingsSalaryIndexRouteImport } from './routes/_app.settings.salary.index'
import { Route as AppSettingsPreferencesIndexRouteImport } from './routes/_app.settings.preferences.index'
import { Route as AppSettingsPositionsIndexRouteImport } from './routes/_app.settings.positions.index'
import { Route as AppSettingsPenaltiesIndexRouteImport } from './routes/_app.settings.penalties.index'
import { Route as AppSettingsLegalIndexRouteImport } from './routes/_app.settings.legal.index'
import { Route as AppSettingsLeavesIndexRouteImport } from './routes/_app.settings.leaves.index'
import { Route as AppSettingsJobTitlesIndexRouteImport } from './routes/_app.settings.job-titles.index'
import { Route as AppSettingsDepartmentsIndexRouteImport } from './routes/_app.settings.departments.index'
import { Route as AppSettingsCommendationsIndexRouteImport } from './routes/_app.settings.commendations.index'
import { Route as AppReportsCadreIndexRouteImport } from './routes/_app.reports.cadre.index'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppPromotionsIndexRoute = AppPromotionsIndexRouteImport.update({
  id: '/promotions/',
  path: '/promotions/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIndexRoute = AppEmployeesIndexRouteImport.update({
  id: '/employees/',
  path: '/employees/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsIndexRoute = AppAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesIdRoute = AppEmployeesIdRouteImport.update({
  id: '/employees/$id',
  path: '/employees/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsSalaryIndexRoute = AppSettingsSalaryIndexRouteImport.update({
  id: '/settings/salary/',
  path: '/settings/salary/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsPreferencesIndexRoute =
  AppSettingsPreferencesIndexRouteImport.update({
    id: '/settings/preferences/',
    path: '/settings/preferences/',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsPositionsIndexRoute =
  AppSettingsPositionsIndexRouteImport.update({
    id: '/settings/positions/',
    path: '/settings/positions/',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsPenaltiesIndexRoute =
  AppSettingsPenaltiesIndexRouteImport.update({
    id: '/settings/penalties/',
    path: '/settings/penalties/',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsLegalIndexRoute = AppSettingsLegalIndexRouteImport.update({
  id: '/settings/legal/',
  path: '/settings/legal/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsLeavesIndexRoute = AppSettingsLeavesIndexRouteImport.update({
  id: '/settings/leaves/',
  path: '/settings/leaves/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsJobTitlesIndexRoute =
  AppSettingsJobTitlesIndexRouteImport.update({
    id: '/settings/job-titles/',
    path: '/settings/job-titles/',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsDepartmentsIndexRoute =
  AppSettingsDepartmentsIndexRouteImport.update({
    id: '/settings/departments/',
    path: '/settings/departments/',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsCommendationsIndexRoute =
  AppSettingsCommendationsIndexRouteImport.update({
    id: '/settings/commendations/',
    path: '/settings/commendations/',
    getParentRoute: () => AppRoute,
  } as any)
const AppReportsCadreIndexRoute = AppReportsCadreIndexRouteImport.update({
  id: '/reports/cadre/',
  path: '/reports/cadre/',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/analytics/': typeof AppAnalyticsIndexRoute
  '/employees/': typeof AppEmployeesIndexRoute
  '/promotions/': typeof AppPromotionsIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/reports/cadre/': typeof AppReportsCadreIndexRoute
  '/settings/commendations/': typeof AppSettingsCommendationsIndexRoute
  '/settings/departments/': typeof AppSettingsDepartmentsIndexRoute
  '/settings/job-titles/': typeof AppSettingsJobTitlesIndexRoute
  '/settings/leaves/': typeof AppSettingsLeavesIndexRoute
  '/settings/legal/': typeof AppSettingsLegalIndexRoute
  '/settings/penalties/': typeof AppSettingsPenaltiesIndexRoute
  '/settings/positions/': typeof AppSettingsPositionsIndexRoute
  '/settings/preferences/': typeof AppSettingsPreferencesIndexRoute
  '/settings/salary/': typeof AppSettingsSalaryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/employees/$id': typeof AppEmployeesIdRoute
  '/analytics': typeof AppAnalyticsIndexRoute
  '/employees': typeof AppEmployeesIndexRoute
  '/promotions': typeof AppPromotionsIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/reports/cadre': typeof AppReportsCadreIndexRoute
  '/settings/commendations': typeof AppSettingsCommendationsIndexRoute
  '/settings/departments': typeof AppSettingsDepartmentsIndexRoute
  '/settings/job-titles': typeof AppSettingsJobTitlesIndexRoute
  '/settings/leaves': typeof AppSettingsLeavesIndexRoute
  '/settings/legal': typeof AppSettingsLegalIndexRoute
  '/settings/penalties': typeof AppSettingsPenaltiesIndexRoute
  '/settings/positions': typeof AppSettingsPositionsIndexRoute
  '/settings/preferences': typeof AppSettingsPreferencesIndexRoute
  '/settings/salary': typeof AppSettingsSalaryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/employees/$id': typeof AppEmployeesIdRoute
  '/_app/analytics/': typeof AppAnalyticsIndexRoute
  '/_app/employees/': typeof AppEmployeesIndexRoute
  '/_app/promotions/': typeof AppPromotionsIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/reports/cadre/': typeof AppReportsCadreIndexRoute
  '/_app/settings/commendations/': typeof AppSettingsCommendationsIndexRoute
  '/_app/settings/departments/': typeof AppSettingsDepartmentsIndexRoute
  '/_app/settings/job-titles/': typeof AppSettingsJobTitlesIndexRoute
  '/_app/settings/leaves/': typeof AppSettingsLeavesIndexRoute
  '/_app/settings/legal/': typeof AppSettingsLegalIndexRoute
  '/_app/settings/penalties/': typeof AppSettingsPenaltiesIndexRoute
  '/_app/settings/positions/': typeof AppSettingsPositionsIndexRoute
  '/_app/settings/preferences/': typeof AppSettingsPreferencesIndexRoute
  '/_app/settings/salary/': typeof AppSettingsSalaryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/employees/$id'
    | '/analytics/'
    | '/employees/'
    | '/promotions/'
    | '/reports/'
    | '/reports/cadre/'
    | '/settings/commendations/'
    | '/settings/departments/'
    | '/settings/job-titles/'
    | '/settings/leaves/'
    | '/settings/legal/'
    | '/settings/penalties/'
    | '/settings/positions/'
    | '/settings/preferences/'
    | '/settings/salary/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/employees/$id'
    | '/analytics'
    | '/employees'
    | '/promotions'
    | '/reports'
    | '/reports/cadre'
    | '/settings/commendations'
    | '/settings/departments'
    | '/settings/job-titles'
    | '/settings/leaves'
    | '/settings/legal'
    | '/settings/penalties'
    | '/settings/positions'
    | '/settings/preferences'
    | '/settings/salary'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/employees/$id'
    | '/_app/analytics/'
    | '/_app/employees/'
    | '/_app/promotions/'
    | '/_app/reports/'
    | '/_app/reports/cadre/'
    | '/_app/settings/commendations/'
    | '/_app/settings/departments/'
    | '/_app/settings/job-titles/'
    | '/_app/settings/leaves/'
    | '/_app/settings/legal/'
    | '/_app/settings/penalties/'
    | '/_app/settings/positions/'
    | '/_app/settings/preferences/'
    | '/_app/settings/salary/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/promotions/': {
      id: '/_app/promotions/'
      path: '/promotions'
      fullPath: '/promotions/'
      preLoaderRoute: typeof AppPromotionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/': {
      id: '/_app/employees/'
      path: '/employees'
      fullPath: '/employees/'
      preLoaderRoute: typeof AppEmployeesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics/': {
      id: '/_app/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AppAnalyticsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/employees/$id': {
      id: '/_app/employees/$id'
      path: '/employees/$id'
      fullPath: '/employees/$id'
      preLoaderRoute: typeof AppEmployeesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/salary/': {
      id: '/_app/settings/salary/'
      path: '/settings/salary'
      fullPath: '/settings/salary/'
      preLoaderRoute: typeof AppSettingsSalaryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/preferences/': {
      id: '/_app/settings/preferences/'
      path: '/settings/preferences'
      fullPath: '/settings/preferences/'
      preLoaderRoute: typeof AppSettingsPreferencesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/positions/': {
      id: '/_app/settings/positions/'
      path: '/settings/positions'
      fullPath: '/settings/positions/'
      preLoaderRoute: typeof AppSettingsPositionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/penalties/': {
      id: '/_app/settings/penalties/'
      path: '/settings/penalties'
      fullPath: '/settings/penalties/'
      preLoaderRoute: typeof AppSettingsPenaltiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/legal/': {
      id: '/_app/settings/legal/'
      path: '/settings/legal'
      fullPath: '/settings/legal/'
      preLoaderRoute: typeof AppSettingsLegalIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/leaves/': {
      id: '/_app/settings/leaves/'
      path: '/settings/leaves'
      fullPath: '/settings/leaves/'
      preLoaderRoute: typeof AppSettingsLeavesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/job-titles/': {
      id: '/_app/settings/job-titles/'
      path: '/settings/job-titles'
      fullPath: '/settings/job-titles/'
      preLoaderRoute: typeof AppSettingsJobTitlesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/departments/': {
      id: '/_app/settings/departments/'
      path: '/settings/departments'
      fullPath: '/settings/departments/'
      preLoaderRoute: typeof AppSettingsDepartmentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/commendations/': {
      id: '/_app/settings/commendations/'
      path: '/settings/commendations'
      fullPath: '/settings/commendations/'
      preLoaderRoute: typeof AppSettingsCommendationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/cadre/': {
      id: '/_app/reports/cadre/'
      path: '/reports/cadre'
      fullPath: '/reports/cadre/'
      preLoaderRoute: typeof AppReportsCadreIndexRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppEmployeesIdRoute: typeof AppEmployeesIdRoute
  AppAnalyticsIndexRoute: typeof AppAnalyticsIndexRoute
  AppEmployeesIndexRoute: typeof AppEmployeesIndexRoute
  AppPromotionsIndexRoute: typeof AppPromotionsIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppReportsCadreIndexRoute: typeof AppReportsCadreIndexRoute
  AppSettingsCommendationsIndexRoute: typeof AppSettingsCommendationsIndexRoute
  AppSettingsDepartmentsIndexRoute: typeof AppSettingsDepartmentsIndexRoute
  AppSettingsJobTitlesIndexRoute: typeof AppSettingsJobTitlesIndexRoute
  AppSettingsLeavesIndexRoute: typeof AppSettingsLeavesIndexRoute
  AppSettingsLegalIndexRoute: typeof AppSettingsLegalIndexRoute
  AppSettingsPenaltiesIndexRoute: typeof AppSettingsPenaltiesIndexRoute
  AppSettingsPositionsIndexRoute: typeof AppSettingsPositionsIndexRoute
  AppSettingsPreferencesIndexRoute: typeof AppSettingsPreferencesIndexRoute
  AppSettingsSalaryIndexRoute: typeof AppSettingsSalaryIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppEmployeesIdRoute: AppEmployeesIdRoute,
  AppAnalyticsIndexRoute: AppAnalyticsIndexRoute,
  AppEmployeesIndexRoute: AppEmployeesIndexRoute,
  AppPromotionsIndexRoute: AppPromotionsIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppReportsCadreIndexRoute: AppReportsCadreIndexRoute,
  AppSettingsCommendationsIndexRoute: AppSettingsCommendationsIndexRoute,
  AppSettingsDepartmentsIndexRoute: AppSettingsDepartmentsIndexRoute,
  AppSettingsJobTitlesIndexRoute: AppSettingsJobTitlesIndexRoute,
  AppSettingsLeavesIndexRoute: AppSettingsLeavesIndexRoute,
  AppSettingsLegalIndexRoute: AppSettingsLegalIndexRoute,
  AppSettingsPenaltiesIndexRoute: AppSettingsPenaltiesIndexRoute,
  AppSettingsPositionsIndexRoute: AppSettingsPositionsIndexRoute,
  AppSettingsPreferencesIndexRoute: AppSettingsPreferencesIndexRoute,
  AppSettingsSalaryIndexRoute: AppSettingsSalaryIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
